SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - Inferno\InfernoConfig\SiteConfig\CustomFooter
SilverStripe\Forms\HTMLEditor\TinyMCEConfig:
  editor_css:
    - 'public/resources/themes/optic/css/opticCMS.css'
SilverStripe\SiteConfig\SiteConfig:
  cms_logo: 'public/resources/themes/optic/image/optic-logo.png'
  cms_logo_width: 100
SilverStripe\Admin\LeftAndMain:
  cms_background: '#521517'
  cms_border_color: '#173778'
  cms_color: '#fff'
  cms_hover_background: '#290B0C'
  cms_active_background: '#3E1011'
  cms_active_color: '#fff'
  cms_drawer_background: '#000000'
SilverStripe\Assets\File:
  allowed_extensions:
    - svg